from tools.build_tools import create_app
from tools.marketplace_tools import create_listing


def run(recipe: dict) -> dict:
    app_name = recipe['name']
    modules = recipe.get('modules', [])
    create_app(app_name, modules)
    create_listing(app_name, f'{app_name} SaaS product generated by THE ONE ecosystem')
    return {'status': 'built', 'app': app_name, 'modules': modules}
