github.com:
    users:
        byfanzoftheone-stack:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: byfanzoftheone-stack
