"""
Forge Engine — generates production-ready app scaffolds from recipes.
Takes a recipe dict and creates a full deployable directory structure.
"""
import json
import shutil
from pathlib import Path
from datetime import datetime, timezone

APPS_DIR    = Path("apps")
RECEIPTS_DIR = Path("warehouse/receipts/forge")

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()

def _write_file(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)

def forge_app(recipe: dict) -> dict:
    """
    Forge a full app scaffold from a recipe dict.
    recipe = {name, modules, stack, description}
    """
    name        = recipe.get("name", "unnamed-app")
    modules     = recipe.get("modules", [])
    stack       = recipe.get("stack", "next-fastapi")
    description = recipe.get("description", f"{name} — generated by THE ONE Forge")

    app_dir = APPS_DIR / name
    if app_dir.exists():
        return {"status": "exists", "app": name, "path": str(app_dir)}

    # ── Directory structure ──────────────────────────────────────────────
    for subdir in ["config", "modules", "docs", "data"]:
        (app_dir / subdir).mkdir(parents=True, exist_ok=True)

    # ── modules.json ────────────────────────────────────────────────────
    _write_file(app_dir / "modules.json", json.dumps({
        "name": name, "version": "1.0.0",
        "description": description, "stack": stack,
        "modules": modules, "created_at": _now()
    }, indent=2))

    # ── README.md ────────────────────────────────────────────────────────
    _write_file(app_dir / "README.md", f"""# {name.replace('-', ' ').title()}

{description}

## Stack
{stack}

## Modules
{chr(10).join(f'- {m}' for m in modules)}

## Generated by
THE ONE Forge Engine · FanzoftheOne
""")

    # ── config/app.json ───────────────────────────────────────────────────
    _write_file(app_dir / "config" / "app.json", json.dumps({
        "app": name, "version": "1.0.0",
        "env": "production", "stack": stack,
        "modules": modules, "description": description
    }, indent=2))

    # ── Forge receipt ─────────────────────────────────────────────────────
    receipt = {"app": name, "modules": modules, "stack": stack, "forged_at": _now(), "status": "forged"}
    RECEIPTS_DIR.mkdir(parents=True, exist_ok=True)
    (RECEIPTS_DIR / f"{name}.json").write_text(json.dumps(receipt, indent=2))

    return {"status": "forged", "app": name, "path": str(app_dir), "modules": modules}


def forge_from_file(recipe_path: str) -> dict:
    recipe = json.loads(Path(recipe_path).read_text())
    return forge_app(recipe)


def forge_batch(recipes: list[dict]) -> list[dict]:
    return [forge_app(r) for r in recipes]


if __name__ == "__main__":
    result = forge_app({
        "name": "test-app",
        "modules": ["crm", "scheduling", "payments"],
        "stack": "next-fastapi",
        "description": "Test app from forge"
    })
    print(json.dumps(result, indent=2))
