"""
Build Tools — creates app scaffolds, generates module lists, validates structure.
"""
import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]

def _now(): return datetime.now(timezone.utc).isoformat()

def create_app(app_name: str, modules: list) -> str:
    app_dir = ROOT / "apps" / app_name
    app_dir.mkdir(parents=True, exist_ok=True)
    (app_dir / "modules.json").write_text(json.dumps({
        "name": app_name, "modules": modules, "created_at": _now()
    }, indent=2))
    (app_dir / "README.md").write_text(
        f"# {app_name.replace('-', ' ').title()}\n\nGenerated by THE ONE build tools.\n\n"
        f"## Modules\n" + "".join(f"- {m}\n" for m in modules)
    )
    (app_dir / "config").mkdir(exist_ok=True)
    (app_dir / "config" / "app.json").write_text(json.dumps({"app": app_name, "version": "1.0.0", "modules": modules}, indent=2))
    return str(app_dir)

def validate_app(app_name: str) -> dict:
    app_dir  = ROOT / "apps" / app_name
    manifest = app_dir / "modules.json"
    readme   = app_dir / "README.md"
    result   = {
        "app":          app_name,
        "exists":       app_dir.exists(),
        "has_manifest": manifest.exists(),
        "has_readme":   readme.exists(),
        "modules":      [],
        "valid":        False,
    }
    if manifest.exists():
        try:
            data = json.loads(manifest.read_text())
            result["modules"] = data.get("modules", [])
        except Exception:
            pass
    result["valid"] = result["exists"] and result["has_manifest"] and len(result["modules"]) > 0
    return result

def list_apps() -> list:
    apps_dir = ROOT / "apps"
    if not apps_dir.exists():
        return []
    return sorted([d.name for d in apps_dir.iterdir() if d.is_dir() and not d.name.startswith(".")])

def app_summary() -> dict:
    apps = list_apps()
    return {
        "total":   len(apps),
        "apps":    apps,
        "valid":   sum(1 for a in apps if validate_app(a)["valid"]),
        "timestamp": _now(),
    }
